services:
  ecu-system:
    build: .
    container_name: ecu_monitor_live
    ports:
      - "8000:8000"
    environment:
      - ECU_MODE=STRICT 
      - TEMP_THRESHOLDS=110.0
      - ECU_MODE=BROKEN
    volumes:
      - ./jenkins_artifacts:/app/output
      - ./data:/app/data